//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DragosWebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class OridiniProdotti
    {
        public int id { get; set; }
        public int idOrdini { get; set; }
        public int idProdotti { get; set; }
        public int quantita { get; set; }
    
        public virtual OrdiniSet OrdiniSet { get; set; }
        public virtual ProdottiSet ProdottiSet { get; set; }
    }
}
